### PR TITLE
Fix changelog date

### PR DESCRIPTION
**Pull request by wbattel4607**
Extremely minor typo that may or may not be worth merging. Up to you!

### CODE REVIEW

**Comment by christocracy** [comment]
Oh shit, I'm still in 2017.  I pushed updates on 4 repos yesterday and probably messed it up on all 4.

**Comment by christocracy** [comment]
Btw customer, you should really get in the habit of using the private repo.  This public version won't see another release for ~3 months.

The private repo will get latest updates.

**Comment by wbattel4607** [comment]
We're considering it. The reason we're currently using this one is that we will only have access to the private repo for a limited time if we don't renew the license annually (the license itself being perpetual but not the repo access), and that we'd have to switch back and forth.

**Comment by christocracy** [comment]
It's not a big job to uninstall / re-install from different repo after a year.

**Comment by christocracy** [comment]
A big bug fix / new feature is going to arrive and you'll be stuck waiting for it to arrive for months.

**Comment by wbattel4607** [comment]
That is true. Moving to the private repo is easy. The larger issue is that when our access terminates we will likely have to downgrade, given that the public version lags behind the private version.

We do monitor both repos and whenever there is a private version we want badly enough we temporarily move over until it's made public, then we switch back over.

**Comment by christocracy** [comment]
You don’t like the support and dedication to innovation you get for a mere $149?

**Comment by wbattel4607** [comment]
No, we like it. The price tag isn't unreasonable by any means. We're just a small tech startup on a shoestring budget that simply can't afford that right now. In the future, that should change, but it's not our highest priority at this time.

**Pull request merged**
