### PR TITLE
Forward declare sqlite3.h (modular framework)

### PR DESCRIPTION
**Pull request by nevir**
Allows ReactNativeBackgroundGeolocation to be built as a framework itself

### CODE REVIEW

**Comment by christocracy** [comment]
Thanks, this is new to me.

**Comment by nevir** [comment]
Also, for more context, I'm using this when including RNBG in a CocoaPods project with its `use_frameworks!` flag on

**Comment by christocracy** [comment]
I can't do this when building the framework, it won't compile.

**Comment by nevir** [comment]
Are you talking about TSLocationManager?  Make sure that you add `#import <sqlite3.h>` to the source file (`LocationDAO.m`?)

**Comment by christocracy** [comment]
Ok, good trick.

**Comment by nevir** [comment]
Yeah, the compiler only needs to know that it's a struct when we compile against the headers; doesn't need to know the shape of it

**Comment by christocracy** [comment]
I've got the `#import <sqlite3.h>` moved and building fine.  I'll be posting an updated version this weekend along with the new [Scheduling Feature](http://shop.transistorsoft.com/blogs/news/98537665-background-geolocation-scheduler)

**Comment by nevir** [comment]
thanks!

**Comment by christocracy** [comment]
Try installing plugin from master.

**Comment by nevir** [comment]
👍 works like a charm

**Pull request closed without merging**
