### PR TITLE
Fixes `removeListeners` promise never resolving on iOS

### PR DESCRIPTION
**Pull request by santiagofm**

### CODE REVIEW

**Comment by christocracy** [comment]
Duplicate #557

**Comment by santiagofm** [comment]
@christocracy When can i expect #557 to be merged? It's a blocker for us...

**Comment by christocracy** [comment]
Just you your own fork if it's a blocker.

**Comment by christocracy** [comment]
And anyway, you don’t even need to wait for that promise to resolve.  The method itself actually *does* perform its task of removing the listeners.

```
BackgroundGeolocation.removeListeners();
```

**Comment by santiagofm** [comment]
Yep, i know. The thing is that i have an `on` that may be called several times and i need to ensure that only one listener is added. In order to do this i'm removing all listeners before calling it, but if i can't await it it won't work. You see an alternative?

#557  hasn't been updated in 2 weeks now that's why i opened this PR, hoping you would close the other one

**Pull request closed without merging**
