### PR TITLE
Fixes a typo in docs.

### PR DESCRIPTION
**Pull request by markrickert**
`BackgroundGeolocaion` -> `BackgroundGeolocation`

This one tripped me up for a second… “i KNOW i copied and pasted right from the docs!” 🤦‍♀️

### CODE REVIEW

**Comment by christocracy** [comment]
Thanks.  Did you generate the html with `./scripts/generate-docs` or did you manually edit the html file?

**Comment by markrickert** [comment]
I manually edited both places where it was misspelled. No doc regeneration.

**Comment by christocracy** [comment]
Ok.  There was no need to edit the html file.  The entire `/doc` folder is auto-generated based upon the typescript declarations.

**Comment by markrickert** [comment]
Ahh cool! Noted for next time! Thanks for the great library! It was great to have geofences already included in thie module and easy implementation!

**Pull request merged**
