### PR TITLE
add cocoa-lumberjack install step

### PR DESCRIPTION
**Pull request by chestercharles**
Add instruction for installation of `cocoa-lumberjack` react-native version < 0.60

### CODE REVIEW

**Comment by christocracy** [comment]
You should *really* avoid the *Manual Setup* and use `react-native link` for `react-native < 0.60`, but ok.  If you have a `Podfile` setup, `react-native link` is going to install the plugin as a Cocoapod, which imports `CocoaLumberjack` [as Cocoapod](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/RNBackgroundGeolocation.podspec#L22), this is much more preferable.

**Comment by chestercharles** [comment]
I abandoned `react-native link` because I was getting
```
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies.
```

when running `react-native link react-native-background-fetch`. This doesn't need to be added to my `package.json` does it?

**Comment by christocracy** [comment]
if `error Unknown dependency.`, simply install it.  It's installed as a dependency of `react-native-background-geolocation` but anything can happen.  Do everything you can to avoid *manual* setup.

**Comment by christocracy** [comment]
You *want* to use Cocoapods.  `react-native >= 0.60` is *all* Cocoapods.

**Comment by chestercharles** [comment]
Got it, I suppose that will be helpful when we finally get around to upgrading from `0.59`.

**Comment by christocracy** [comment]
There is pain upgrading to `0.60` but once you do, everything is much easier with iOS being *all* cocoapods.

**Pull request merged**
