### PR TITLE
Update docs for Expo v50

### PR DESCRIPTION
**Pull request by vonkanehoffen**
See #1710

### CODE REVIEW

**Comment by christocracy** [comment]
The latest version of [play-services-location is `22.1.0`](https://maven.google.com/web/m_index.html?q=Location#com.google.android.gms:play-services-location:21.1.0).

Why stay a version back?

**Comment by vonkanehoffen** [comment]
Sorry @christocracy I had no idea 😂  ...was just going off your comment on that old issue.

21.1.0 also seems fine with Expo 50.

**Comment by christocracy** [comment]
It's important to understand that Google Play Services is Android's proprietary extensions of the Android OS.  It's important for you the developer to ensure you're using the latest available APIs from Google.  The plug-in exposes these variables to allow you to do so.

**Comment by Namec999** [comment]
now every thing is OK

it's working only with expo-dev-client not with the regular expo Go app

thanks for your support

you'll hear a lot from me in the next few hours :-) sorry for that lol

**Pull request merged**
