### PR TITLE
Fix getLocations typings

### PR DESCRIPTION
**Pull request by nabati**
I think this should be correct. Are there any type tests in the project?

### CODE REVIEW

**Comment by christocracy** [comment]
Sorry, can't apply the `Location` type here since the developer may have defined a `locationTemplate`.

**Comment by nabati** [comment]
🤔

Could you explain how that is relevant? The documentation says 
```
Retrieve a List of Location currently stored in the plugin's SQLite database.
```
yet it returns an array of Object. 

For [locationTemplate](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#locationtemplate), it seems related to rendering for HTTP requests, and I don't see the connection here.

**Comment by christocracy** [comment]
The plugin persists a JSON blob of location data in the db.  If a locationTemplate is applied, it’s impossible to coerce that data into a Location instance.

**Comment by nabati** [comment]
How about providing an overloaded signature to the method? Not sure the below works exactly, but something like
```
static getLocations<T>(success?:(locations:Array<T>) => void, failure?:Function): Promise<Array<T>>;
```

**Pull request closed without merging**
